version: '3.4'

services:
#########################################################################################################################
# DEPENDENCIES
#########################################################################################################################
   
  blogpost-seq:
    image: datalust/seq:latest
    container_name: blogpost
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341" 
      - "8081:80"  